globals:
    window: true
env:
    browser: true
    es2022: true
    node: true
    jest: true
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: ./tsconfig.json
    ecmaFeatures:
        jsx: true
settings:
    react:
        version: detect
extends:
    - plugin:@typescript-eslint/recommended
    - next/core-web-vitals
    - airbnb
    - airbnb-typescript
    - airbnb/hooks
    - plugin:react/recommended
    - plugin:react-hooks/recommended
    - plugin:jsx-a11y/recommended
    - plugin:testing-library/react
    - prettier
plugins:
    - '@typescript-eslint'
    - react
    - react-hooks
    - simple-import-sort
    - testing-library
overrides:
    - files:
          - '**/__TESTS__/*.[jt]s?(x)'
          - '**/?(*.)+(spec|test).[jt]s?(x)'
      extends:
          - plugin:testing-library/react
rules:
    indent:
        - error
        - tab
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-console:
        - error
    import/extensions:
        - off
    no-plusplus:
        - off
    react/require-default-props:
        - off
    react/jsx-no-bind:
        - off
    react/jsx-props-no-spreading:
        - off
    react/jsx-filename-extension:
        - 2
        - extensions:
              - .js
              - .jsx
              - .ts
              - .tsx
    import/no-extraneous-dependencies:
        - off
    simple-import-sort/imports:
        - error
    simple-import-sort/exports:
        - error
    no-unused-vars:
        - off
    '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: ^_
    prefer-arrow-callback:
        - off
    react/function-component-definition:
        - 2
        - namedComponents:
            - arrow-function
            - function-declaration
    arrow-body-style: 0
    no-restricted-exports:
        - off