import Head from 'next/head';
import React from 'react';

import ComicList from '../components/ComicList';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Hero from '../components/Hero';
import Intro from '../components/Intro';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Comic Closet</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<Header />
			<main>
				<Hero />
				<Intro />
				<ComicList />
			</main>
			<Footer />
		</div>
	);
}
