import Head from 'next/head';
import React, { useEffect } from 'react';

import ComicComponent from '../components/Comic';
import useMarvel from '../hooks/useMarvel';
import { Comic } from '../types/Comic';

export default function Home() {
	const { loading, error, data, getComics } = useMarvel();

	useEffect(() => {
		getComics();
	}, []); /* eslint-disable-line react-hooks/exhaustive-deps */

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>

			<main
				style={{
					display: 'grid',
					gridTemplateColumns:
						'repeat(auto-fill, minmax(183px, auto))',
					gridColumnGap: 20,
					gridRowGap: 60,
					justifyContent: 'center',
				}}
			>
				{loading && <p>Loading...</p>}
				{error && <p>Error</p>}
				{!loading &&
					!error &&
					!!data?.results &&
					data.results.map((comic: Comic) => (
						<ComicComponent
							key={comic.id}
							comic={comic}
						/>
					))}
			</main>

			<footer>
				<p>Data provided by Marvel. © 2014 Marvel</p>
			</footer>
		</div>
	);
}
